version: "3.8"

services:
  # sqlite:
  #   image: nouchka/sqlite3
  #   volumes:
  #     - sqlite-data:/root/db
  #     - ./init-scripts:/docker-entrypoint-initdb.d # Mount initialization scripts
  #   command: [ "sqlite3", "/root/db/sqlite.db", "-cmd", ".tables" ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  qdrant:
    image: generall/qdrant:latest
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "minioadmin" # Customize access key
      MINIO_ROOT_PASSWORD: "minioadmin" # Customize secret key
    command: server /data
    ports:
      - "9000:9000" # Console access
      - "9001:9001" # API access
    volumes:
      - minio-data:/data

  flask_app:
    # build: . # Directory with Dockerfile for Flask app
    image: kastanday/ai-ta-backend:gunicorn
    ports:
      - "8000:8000"
    volumes:
      - ./db:/usr/src/app/db # Mount local directory to store SQLite database
    depends_on:
      # - sqlite
      - redis
      - qdrant
      - minio

volumes:
  # sqlite-data:
  redis-data:
  qdrant-data:
  minio-data:
