services:
  redis:
    image: redis:7.2
    restart: unless-stopped
    container_name: redis
    command: redis-server --requirepass ${INGEST_REDIS_PASSWORD}
    # ports:
    #   - 6379:6379
    networks:
      - my-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.9.5
    restart: unless-stopped
    container_name: qdrant
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/production.yaml # Mount the config file directly as a volume
    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-H",
          "Authorization: Bearer qd-SbvSWrYpa473J33yPjdL",
          "http://localhost:6333/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    restart: unless-stopped
    container_name: minio
    # Customize env vars in .env file
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data --address ":10000" --console-address ":10001"
    ports:
      - ${PUBLIC_MINIO_API_PORT}:10000
      - ${PUBLIC_MINIO_DASHBOARD_PORT}:10001
    networks:
      - my-network
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  flask-app:
    build: . # Directory with Dockerfile for Flask app
    # image: kastanday/ai-ta-backend:gunicorn
    restart: unless-stopped
    container_name: flask-app
    ports:
      - "${FLASK_PORT}:8000"
    volumes:
      - ./db:/usr/src/app/db # Mount local directory to store SQLite database
    networks:
      - my-network
    depends_on:
      - qdrant
      - redis
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  ingest-worker:
    build: . # Use the same build context as the Flask app
    command: python ai_ta_backend/redis_queue/worker.py
    restart: unless-stopped
    container_name: ingest-worker
    networks:
      - my-network
    depends_on:
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "from redis import Redis; from rq import Worker; r = Redis(host='redis', port=6379, password='${INGEST_REDIS_PASSWORD}'); exit(0 if Worker.count(r) > 0 else 1)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

# declare the network resource
# this will allow you to use service discovery and address a container by its name from within the network
networks:
  my-network: {}

volumes:
  redis-data: {}
  qdrant-data: {}
  minio-data: {}
