services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:v1.9.5
    restart: always
    container_name: qdrant
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/production.yaml # Mount the config file directly as a volume
    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-H",
          "Authorization: Bearer qd-SbvSWrYpa473J33yPjdL",
          "http://localhost:6333/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    # Customize env vars in .env file
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - 9000:9000 # Console access
      - 9001:9001 # API access
    networks:
      - my-network
    volumes:
      - minio-data:/data

  flask_app:
    container_name: flask-ta-backend
    build: . # Directory with Dockerfile for Flask app
    ports:
      - "${FLASK_PORT}:8000"
    expose:
      - "${FLASK_PORT}"
    volumes:
      - ./db:/usr/src/app/db # Mount local directory to store SQLite database
    networks:
      - my-network
      - supabase_default # Add connection to Supabase network
    depends_on:
      - qdrant
      - redis
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 10

# declare the network resource
# this will allow you to use service discovery and address a container by its name from within the network
networks:
  my-network: {}
  supabase_default:
    external: true # Mark as external since it's managed by Supabase

volumes:
  redis-data: {}
  qdrant-data: {}
  minio-data: {}
